version: '3'
services:
  tor-bart:
    container_name: 'tor-bart'
    image: 'zhaowde/rotating-tor-http-proxy'
    ports:
      - '9990:3128'
    restart: always
  tor-homer:
    container_name: 'tor-homer'
    image: 'zhaowde/rotating-tor-http-proxy'
    ports:
      - '9991:3128'
    restart: always
  tor-marge:
    container_name: 'tor-marge'
    image: 'zhaowde/rotating-tor-http-proxy'
    ports:
      - '9992:3128'
    restart: always
  tor-lisa:
    container_name: 'tor-lisa'
    image: 'zhaowde/rotating-tor-http-proxy'
    ports:
      - '9993:3128'
    restart: always
